services:
  client:
    image: client
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    image: server
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
    volumes:
      - ./server:/app
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data
  test_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
  e2e:
    build:
      context: ./e2e
    depends_on:
      - client
    volumes:
      - ./e2e:/e2e
volumes:
  db-data:
